<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<NoWarn>SA1405</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Buffers\Buffers.csproj" />
	</ItemGroup>

</Project>
